package com.nt.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import com.nt.entity.Student;
import com.nt.dao.StudentDao;
import com.nt.payloads.StudentRequestDto;
import com.nt.payloads.StudentResponseDto;

@Service
public class StudentService {

	@Autowired
	private StudentDao studentDao;

	public void addStudent(StudentRequestDto studentDto) {
		Student student = new Student();
		// Note: Assuming that the ID is generated by the database (auto-increment).
		// So, we don't set the ID explicitly here.
		student.setName(studentDto.getName());
		student.setBranch(studentDto.getBranch());
		student.setAge(studentDto.getAge());
		studentDao.save(student);
	}
	public void updateStudent(StudentRequestDto studentRequestDto) {
		Student student = new Student();
		student.setName(studentRequestDto.getName());
		student.setBranch(studentRequestDto.getBranch());
		student.setAge(studentRequestDto.getAge());
		studentDao.save(student);

	}

	public void deleteStudent(int id) {
		
		studentDao.deleteAll();
	}
	public List<StudentResponseDto> allstudent() {
		List<Student> list = studentDao.findAll();
		List<StudentResponseDto> dtos = new ArrayList<>();
		
		for(Student student : list) {
			StudentResponseDto dto = new StudentResponseDto();
			dto.setAge(student.getAge());
			dto.setBranch(student.getBranch());
			dto.setName(student.getName());
			dto.setStudentId(student.getStudentId());
			dtos.add(dto);
		}
		return dtos;
	}
	
	
	public StudentResponseDto getById(int id) {
		Optional<Student> opt = studentDao.findById(id);
		
		if(opt.isPresent()) {
			Student student = opt.get();
			StudentResponseDto dto = new StudentResponseDto();
			dto.setAge(student.getAge());
			dto.setBranch(student.getBranch());
			dto.setName(student.getName());
			dto.setStudentId(student.getStudentId());
			return dto;
		}
		return null;
	}

}
